/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AjoutJFrame2.java
 *
 * Created on 6 mars 2012, 14:40:37
 */
package IHMClient;

import java.awt.Color;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.util.List;
import javax.swing.JOptionPane;
import modele.Artiste;
import modele.Oeuvre;
import service.Service;

/**
 *
 * @author Administrateur
 */
public class AjoutPartie2JFrame extends javax.swing.JFrame {

    /** Creates new form AjoutJFrame2 */
    public AjoutPartie2JFrame() {

        initComponents();
        service = new Service();
        computeBounds();

        //Préparation de la comboBox d'artistes
        lesArtistes = service.rechercherTousArtistes();
        for (Artiste unArtiste : lesArtistes) {
            StringBuilder buffer = new StringBuilder();
            buffer.append(unArtiste.getPrenom());
            buffer.append(" ");
            buffer.append(unArtiste.getNom());
            jComboBoxArtiste.addItem(buffer);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar = new javax.swing.JToolBar();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        labelArtiste = new javax.swing.JLabel();
        jTextNom = new javax.swing.JTextField();
        labelNom = new javax.swing.JLabel();
        labelTitre = new javax.swing.JLabel();
        labelPrix = new javax.swing.JLabel();
        jTextPrix = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCar1 = new javax.swing.JTextArea();
        labelCar = new javax.swing.JLabel();
        jComboBoxArtiste = new javax.swing.JComboBox();
        jButtonAjouter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Creat'IF");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage("art2.png"));

        jToolBar.setFloatable(false);
        jToolBar.setRollover(true);

        jButton5.setText("Accueil");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar.add(jButton5);

        jButton1.setText("Ajouter une oeuvre");
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar.add(jButton1);

        jButton2.setText("Consulter le planning");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar.add(jButton2);

        labelArtiste.setText("Artiste :");

        jTextNom.setColumns(20);
        jTextNom.setToolTipText("Le nom ne doit pas etre vide");

        labelNom.setText("Nom :");

        labelTitre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTitre.setText("Ajouter une oeuvre");

        labelPrix.setText("Prix :");

        jTextPrix.setColumns(10);
        jTextPrix.setToolTipText("Le prix ne peut pas être vide. Le caractère . est utilisé");

        jTextAreaCar1.setColumns(20);
        jTextAreaCar1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextAreaCar1.setLineWrap(true);
        jTextAreaCar1.setRows(3);
        jScrollPane1.setViewportView(jTextAreaCar1);

        labelCar.setText("Caractéristiques :");

        jComboBoxArtiste.setMaximumRowCount(4);
        jComboBoxArtiste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxArtisteActionPerformed(evt);
            }
        });

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(labelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelArtiste)
                    .addComponent(labelNom)
                    .addComponent(labelCar)
                    .addComponent(labelPrix))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxArtiste, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNom)
                    .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArtiste)
                    .addComponent(jComboBoxArtiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labelCar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrix))
                .addGap(51, 51, 51)
                .addComponent(jButtonAjouter)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new AccueilJFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "Fonctionnalité non implémentée");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxArtisteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxArtisteActionPerformed
    {//GEN-HEADEREND:event_jComboBoxArtisteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxArtisteActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAjouterActionPerformed
    {//GEN-HEADEREND:event_jButtonAjouterActionPerformed
        boolean validite = true;
        String nom = jTextNom.getText();
        if(nom.isEmpty())
        {
            jTextNom.setBackground(Color.RED);
            validite = false;
        }
        else
        {
            jTextNom.setBackground(Color.WHITE);
        }
         
        float prix = 0;
        try {
            prix = Float.parseFloat(jTextPrix.getText());
            jTextPrix.setBackground(Color.WHITE);
        } catch (NumberFormatException e) {
            jTextPrix.setBackground(Color.RED);
            validite = false;
        }

        if(validite)
        {
            String caract = jTextAreaCar1.getText();
            //Récupération du bon artiste
            Artiste unArtiste = lesArtistes.get(jComboBoxArtiste.getSelectedIndex());
            Oeuvre uneOeuvre = new Oeuvre(nom, caract, prix);

            if (service.creerOeuvre(uneOeuvre, unArtiste) == 0) {
                JOptionPane.showMessageDialog(null, "Ajout correctement effectué");
                new AjoutPartie1JFrame().setVisible(true);
                dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Ajout impossible");
            }
        }
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    /**
     * @param args the command line arguments
     *
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AjoutPartie2JFrame().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JComboBox jComboBoxArtiste;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaCar1;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JTextField jTextPrix;
    private javax.swing.JToolBar jToolBar;
    private javax.swing.JLabel labelArtiste;
    private javax.swing.JLabel labelCar;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelPrix;
    private javax.swing.JLabel labelTitre;
    // End of variables declaration//GEN-END:variables
    Service service;
    //Variable nécessaire pour afficher et traiter la liste déroulante d'artistes
    List<Artiste> lesArtistes;

    //Dimensionnement de la fenetre
    private void computeBounds()
    {
        Rectangle screen = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
        Rectangle actualScreen = getBounds();
        Rectangle bounds = new Rectangle((int)(screen.getWidth() - actualScreen.getWidth()) / 2,(int) (screen.getHeight() - actualScreen.getHeight()) /2, (int) actualScreen.getWidth(), (int) actualScreen.getWidth());
       
        setBounds(bounds);
    }
}
