/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsulterPartie2JFrame.java
 *
 * Created on 6 mars 2012, 15:50:01
 */

package IHMClient;

/**
 *
 * @author Administrateur
 */
public class ConsulterPartie2JFrame extends javax.swing.JFrame {

    /** Creates new form ConsulterPartie2JFrame */
    public ConsulterPartie2JFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonAccueil = new javax.swing.JButton();
        jButtonAjoutOeuvre = new javax.swing.JButton();
        jButtonConsultation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setEnabled(false);

        jButtonAccueil.setText("Accueil");
        jButtonAccueil.setFocusable(false);
        jButtonAccueil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAccueil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccueilActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAccueil);

        jButtonAjoutOeuvre.setText("Ajouter une oeuvre");
        jButtonAjoutOeuvre.setFocusable(false);
        jButtonAjoutOeuvre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAjoutOeuvre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAjoutOeuvre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutOeuvreActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAjoutOeuvre);

        jButtonConsultation.setText("Consulter le planning");
        jButtonConsultation.setEnabled(false);
        jButtonConsultation.setFocusable(false);
        jButtonConsultation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonConsultation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonConsultation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultationActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonConsultation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccueilActionPerformed
        new AccueilJFrame().setVisible(true);
        dispose();
}//GEN-LAST:event_jButtonAccueilActionPerformed

    private void jButtonConsultationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultationActionPerformed

}//GEN-LAST:event_jButtonConsultationActionPerformed

    private void jButtonAjoutOeuvreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutOeuvreActionPerformed
        new AjoutPartie1JFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAjoutOeuvreActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsulterPartie2JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccueil;
    private javax.swing.JButton jButtonAjoutOeuvre;
    private javax.swing.JButton jButtonConsultation;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
